apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlopsapp
spec:
  selector:
    matchLabels:
      app: mlopsapp
  template:
    metadata:
      labels:
        app: mlopsapp
    spec:
      containers:
      - name: mlopsappcontainer
        image: pavanvarikolu/mlopsproject:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

---
kind: Service
apiVersion: v1
metadata:
  name: mlopsapp-service
spec:
  selector:
    app: mlopsapp
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
