apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontainer
  labels:
    app: mycontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycontainer
  template:
    metadata:
      labels:
        app: mycontainer
    spec:
      containers:
      - name: mycontainer
        image: pavanvarikolu/mlopsproject:v1.0.0
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: mycontainer-service
spec:
  selector:
    app: mycontainer
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000